[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 500000
fs_permissions = [{ access = "read", path = "./out"}]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
base = "${BASE_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config